#!/usr/bin/env python3
"""
AI Report Generator - Phase B.5

Generates professional bug bounty reports:
- Executive summary
- Detailed findings with PoC
- Impact analysis
- Remediation recommendations
- Ready for submission to bug bounty platforms
"""
import sys, os, json
from pathlib import Path
from datetime import datetime
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).parent.parent))
from base import Finding, ResultWriter

class AIReportGenerator:
    """Generate professional bug bounty reports"""
    
    def __init__(self, target, output_dir="reports"):
        self.target = target
        self.output_dir = output_dir
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        self.findings = []
    
    def load_prioritized_findings(self) -> List[Dict]:
        """Load prioritized findings"""
        findings = []
        
        submission_file = "results/prioritized/submission_list.json"
        if os.path.exists(submission_file):
            try:
                with open(submission_file) as f:
                    data = json.load(f)
                    findings = data.get("priority_ranking", [])
            except:
                pass
        
        return findings
    
    def generate_markdown_report(self, findings: List[Dict]) -> str:
        """Generate Markdown report"""
        report = []
        
        # Header
        report.append(f"# Security Assessment Report")
        report.append(f"")
        report.append(f"**Target:** {self.target}")
        report.append(f"**Date:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
        report.append(f"**Total Findings:** {len(findings)}")
        report.append(f"")
        
        # Executive Summary
        report.append(f"## Executive Summary")
        report.append(f"")
        
        severity_count = {}
        for f in findings:
            sev = f.get("severity", "info")
            severity_count[sev] = severity_count.get(sev, 0) + 1
        
        report.append(f"### Findings by Severity")
        for sev in ["critical", "high", "medium", "low", "info"]:
            if sev in severity_count:
                report.append(f"- **{sev.upper()}**: {severity_count[sev]}")
        report.append(f"")
        
        # Detailed Findings
        report.append(f"## Detailed Findings")
        report.append(f"")
        
        for i, finding in enumerate(findings, 1):
            report.append(f"### {i}. {finding.get('title', 'Unknown Finding')}")
            report.append(f"")
            report.append(f"**Severity:** {finding.get('severity', 'Unknown')}")
            report.append(f"**Category:** {finding.get('category', 'Unknown')}")
            report.append(f"**Target:** `{finding.get('target', 'N/A')}`")
            report.append(f"")
            
            report.append(f"#### Description")
            report.append(f"{finding.get('description', 'No description available')}")
            report.append(f"")
            
            if finding.get("remediation"):
                report.append(f"#### Remediation")
                report.append(f"{finding['remediation']}")
                report.append(f"")
            
            report.append(f"---")
            report.append(f"")
        
        # Footer
        report.append(f"## Methodology")
        report.append(f"")
        report.append(f"This assessment was conducted using BugBountyCI Modular v2.0, which includes:")
        report.append(f"- Automated reconnaissance and attack surface mapping")
        report.append(f"- AI-powered endpoint discovery and secret hunting")
        report.append(f"- Business logic analysis")
        report.append(f"- Attack chain correlation")
        report.append(f"- Intelligent triage and validation")
        report.append(f"")
        report.append(f"---")
        report.append(f"")
        report.append(f"*Report generated by BugBountyCI v2.0*")
        
        return "\n".join(report)
    
    def generate_json_report(self, findings: List[Dict]) -> Dict:
        """Generate JSON report"""
        return {
            "target": self.target,
            "generated_at": datetime.utcnow().isoformat(),
            "total_findings": len(findings),
            "findings": findings,
            "metadata": {
                "tool": "BugBountyCI",
                "version": "2.0.0",
                "methodology": "Automated + AI-powered assessment"
            }
        }
    
    def save_reports(self, findings: List[Dict]):
        """Save reports in multiple formats"""
        # Markdown
        md_report = self.generate_markdown_report(findings)
        md_file = f"{self.output_dir}/report_{self.target}_{datetime.utcnow().strftime('%Y%m%d')}.md"
        with open(md_file, "w") as f:
            f.write(md_report)
        print(f"[+] Markdown report: {md_file}")
        
        # JSON
        json_report = self.generate_json_report(findings)
        json_file = f"{self.output_dir}/report_{self.target}_{datetime.utcnow().strftime('%Y%m%d')}.json"
        with open(json_file, "w") as f:
            json.dump(json_report, f, indent=2)
        print(f"[+] JSON report: {json_file}")
        
        # Summary
        summary_file = f"{self.output_dir}/summary.txt"
        with open(summary_file, "w") as f:
            f.write(f"Bug Bounty Report Summary\n")
            f.write(f"{'='*60}\n")
            f.write(f"Target: {self.target}\n")
            f.write(f"Date: {datetime.utcnow().strftime('%Y-%m-%d')}\n")
            f.write(f"Total Findings: {len(findings)}\n\n")
            
            for i, finding in enumerate(findings[:10], 1):
                f.write(f"{i}. [{finding.get('severity', 'N/A').upper()}] {finding.get('title', 'Unknown')}\n")
                f.write(f"   Target: {finding.get('target', 'N/A')}\n\n")
        
        print(f"[+] Summary: {summary_file}")
    
    def run(self):
        """Generate reports"""
        print(f"\n{'='*80}")
        print(f"AI REPORT GENERATOR")
        print(f"Target: {self.target}")
        print(f"{'='*80}\n")
        
        # Load findings
        findings = self.load_prioritized_findings()
        
        if not findings:
            print("[!] No findings to report")
            return
        
        # Generate reports
        self.save_reports(findings)
        
        print(f"\n{'='*80}")
        print(f"Report Generation Complete")
        print(f"   Findings included: {len(findings)}")
        print(f"{'='*80}\n")
        
        return findings

def main(target, output_dir="reports"):
    generator = AIReportGenerator(target, output_dir)
    return generator.run()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <target>")
        sys.exit(1)
    main(sys.argv[1])
